2020-11-26 GUARD-906 GUARD-893 Combined-Release
skuvault/netsuiteAccess pull request #27
Opened 2020-11-26 13:51 UTC by fabulaspb

**GUARD-893:**
Current SendTimeout value for SOAP client is not enough to pull all purchase orders from MFI Medicals's NetSuite account.
https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.channels.binding.sendtimeout?view=dotnet-plat-ext-3.1
I've implemented workaround, when access library gets timeout exception, it decreases page size. Works well.

**GUARD-906:**
Following NetSuite documentation, renamed "pending bill" purchase order status to "pending billing".
https://system.netsuite.com/help/helpcenter/en_US/srbrowser/Browser2019_2/schema/enum/purchaseorderorderstatus.html?mode=package

2020-12-01 16:06 UTC, maxim-skuvault reviewed
@fabulaspb , GUARD-906 looks good.
GUARD-893: I only see the code and tests for reducing the page size. It appears that we never increase the page size while processing the same "Get POs" request that triggered the page size reduction. Once page size gets to 1, we just rethrow from the catch() and I presume it fails the sync? We don't continue the sync? Won't the next sync run throw on the same PO and this will keep happening indefinitely?

2020-12-01 16:07 UTC, maxim-skuvault commented on src/NetSuiteAccess/Services/Soap/NetSuiteSoapService.cs
> +						throw ex;
@fabulaspb , Since when `currentPageSize == 1` we've presumably reached the item that causes the error, don't we want to log the current item index, for further troubleshooting?

2020-12-02 10:24 UTC, fabulaspb commented on src/NetSuiteAccess/Services/Soap/NetSuiteSoapService.cs
> +						throw ex;
@maxim-skuvault Yes, we never increase the page size back after receiving TimeoutException. In NetSuite case, we don't have some "problem" PO like ShipStation case. I assume that in some cases NetSuite server requires too much resources to handle our standard request with default page size. This can be caused by connected custom scripts to purchase order entity. So, just decreasing page size twice should be really enough to solve our issue. If NetSuite server is unable to return purchase orders with page size 1 throwing TimeoutException, sync will be stopped.

2020-12-02 16:24 UTC, maxim-skuvault commented on src/NetSuiteAccess/Services/Soap/NetSuiteSoapService.cs
> +						throw ex;
Thanks for explaining. Can you respond to my comment about logging the index of the current item on `throw ex`: https://github.com/skuvault/netsuiteAccess/pull/27#discussion_r533533054 ?

2020-12-28 00:11 UTC, slav commented on src/NetSuiteAccess/Services/Soap/NetSuiteSoapService.cs
> +						throw ex;
@fabulaspb - is this documented in the code somewhere?

2021-01-05 14:08 UTC, jnewman-sv requested changes
Please see comment on exception filters - ActionPolicy.cs

2021-01-05 16:09 UTC, maxim-skuvault commented on src/NetSuiteAccess/Throttling/ActionPolicy.cs
> +
@jnewman-sv , I love this. And it's available in C# 6🤯 . Per this (https://thomaslevesque.com/2015/06/21/exception-filters-in-c-6/) we need to be careful to still keep the "fall through" generic `catch(Exception ex)` (as you do above). Otherwise, the exception will just bubble up

2021-01-22 14:12 UTC, merged